easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - name
                    - description
                    - price
                    - isPublished
                    - imageName
                    - category
                    - publisher
                    - tags
            list:
                fields: ['name', 'price', 'category', 'isPublished', 'imageName']
        Categories:
            class: App\Entity\Category
        Utilisateurs:
            class: App\Entity\User
    site_name: 'symfony perfectionnement'

